
  export const Adminrows = [
    { id: 1, 
    firstname:"Juanito",
    lastname:"Perez",
    Username: "Admin1", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"SuperAdimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 2, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin2", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 3, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin3", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg", 
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 4, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin4", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",   
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 5, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin5", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",    
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 6, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin6", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 7, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin7", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 8, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin8", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",    
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 9, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin9", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
   { id: 10, 
    firstname:"Juanito ",
    lastname:"Perez",
    Username: "Admin10", 
    avatar:
    "https://www.certus.edu.pe/blog/wp-content/uploads/2019/11/certus-en-que-puede-trabajar-administrador-empresas-1200x720.jpg",
    email:"Adimn@gmail.com", 
    area:"Gerencia",
    status:"active",
   },
  ];